name: Mise à jour prix climatisation

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests beautifulsoup4
      - run: python scraper.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Prix mis à jour automatiquement"
          file_pattern: "index.html toshiba/index.html daikin/index.html mitsubishi/index.html atlantic/index.html lg/index.html samsung/index.html historique.json"
